# Dockerfile
FROM python:3.12-slim

# Workdir
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencie
RUN pip install --no-cache-dir -r requirements.txt

# Copy project code
COPY . .

# Expose port
EXPOSE 8000

# Run Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
